"""Signal Bus for Chintu AI Proactivity."""

import logging
import asyncio
from typing import Dict, List, Callable, Any, Optional
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)

class SignalType(Enum):
    SYSTEM = "system"        # Hardware, battery, internet
    CALENDAR = "calendar"    # Upcoming meetings
    EMAIL = "email"          # New important emails
    TASK = "task"            # Deadline approaching
    USER_IDLE = "user_idle"  # User hasn't interacted but pc is on
    NEWS = "news"            # Breaking news on watched topics
    SKILL = "skill"          # New skill discovered/updated
    PROJECT = "project"      # File system changes in workspace

class Signal:
    """A proactive signal generated by a sensor."""
    def __init__(self, signal_type: SignalType, source: str, data: Dict[str, Any], priority: int = 1):
        self.signal_type = signal_type
        self.source = source
        self.data = data
        self.priority = priority
        self.timestamp = datetime.now()

class SignalBus:
    """
    Central event distribution for proactive agents.
    Allows specialized sensors (Observers) to emit signals
    that specialized Agents can subscribe to.
    """
    def __init__(self):
        self._subscribers: Dict[SignalType, List[Callable]] = {t: [] for t in SignalType}
        self._history: List[Signal] = []
        self._max_history = 100

    def subscribe(self, signal_type: SignalType, callback: Callable[[Signal], Any]):
        """Subscribe a handler to a specific signal type."""
        if callback not in self._subscribers[signal_type]:
            self._subscribers[signal_type].append(callback)
            logger.info(f"Subscribed handler to signal: {signal_type.value}")

    async def emit(self, signal: Signal):
        """Emit a signal to all subscribers."""
        logger.info(f"Signal Emitted: {signal.signal_type.value} from {signal.source}")
        
        # Track history
        self._history.append(signal)
        if len(self._history) > self._max_history:
            self._history.pop(0)

        # Notify subscribers
        tasks = []
        for callback in self._subscribers[signal.signal_type]:
            if asyncio.iscoroutinefunction(callback):
                tasks.append(callback(signal))
            else:
                # Run sync callback in thread to avoid blocking bus
                loop = asyncio.get_event_loop()
                tasks.append(loop.run_in_executor(None, callback, signal))
        
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)

# Global singleton
_bus: Optional[SignalBus] = None

def get_signal_bus() -> SignalBus:
    """Get or create the global SignalBus instance."""
    global _bus
    if _bus is None:
        _bus = SignalBus()
    return _bus
