"""
Code Interpreter Module.
Implements safe Python execution with iterative self-repair and learning hooks.
"""

from __future__ import annotations

import ast
import logging
import math
import random
import re
import tempfile
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .config import get_config
from .safe_exec import get_safe_executor

logger = logging.getLogger(__name__)


@dataclass
class CodeSolveResult:
    success: bool
    output: str = ""
    error: str = ""
    attempts: int = 0
    script_path: str = ""
    attempt_errors: List[str] = field(default_factory=list)
    learned: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": bool(self.success),
            "output": self.output,
            "error": self.error,
            "attempts": int(self.attempts),
            "script_path": self.script_path,
            "attempt_errors": list(self.attempt_errors or []),
            "learned": dict(self.learned or {}),
        }


class CodeInterpreter:
    """
    Safely executes Python code generated by the LLM.
    Used when rigid capabilities fail or for complex data tasks.
    """

    def __init__(self, llm_client=None):
        self.config = get_config()
        self.executor = get_safe_executor()
        self.llm = llm_client
        self.max_attempts = max(1, int(getattr(self.config, "code_interpreter_max_attempts", 3)))
        self.timeout_seconds = max(5, int(getattr(self.config, "code_interpreter_timeout_seconds", 30)))

        if not self.llm:
            try:
                from ..brain.llm.ollama_client import OllamaClient

                self.llm = OllamaClient()
            except Exception:
                self.llm = None

    def solve(self, goal: str, context: Optional[Dict[str, Any]] = None) -> str:
        """Backwards-compatible string API."""
        result = self.solve_with_metadata(goal, context=context)
        if context is not None and isinstance(context, dict):
            try:
                context["_code_interpreter_meta"] = result.to_dict()
            except Exception:
                pass
        if result.success:
            return result.output
        return result.error or "Failed to generate valid code for this task."

    def solve_with_metadata(self, goal: str, context: Optional[Dict[str, Any]] = None) -> CodeSolveResult:
        """
        1) Generate or extract Python code.
        2) Run in safe executor.
        3) Retry with error-aware repair when needed.
        4) Record learning gaps for future improvement.
        """
        context = context or {}
        goal_text = str(goal or "").strip()
        if not goal_text:
            return CodeSolveResult(success=False, error="Missing goal for code interpreter.")

        deterministic = self._deterministic_solve(goal_text)
        if deterministic is not None:
            return CodeSolveResult(
                success=True,
                output=deterministic,
                attempts=1,
                script_path="",
                attempt_errors=[],
            )

        inline_code = self._extract_inline_code(goal_text)
        if inline_code:
            code = inline_code
        else:
            if not self.llm or not hasattr(self.llm, "generate"):
                return CodeSolveResult(success=False, error="No LLM available to generate code for this task.")
            code = self._generate_code(goal_text, context)

        if not code:
            return CodeSolveResult(success=False, error="Failed to generate executable code.")

        attempt_errors: List[str] = []
        final_script_path = ""
        last_error = ""

        for attempt in range(1, self.max_attempts + 1):
            is_safe, reason = self._is_safe_code(code)
            if not is_safe:
                last_error = f"Security Block: {reason}"
                attempt_errors.append(last_error)
                break

            script_path, write_err = self._write_script(code=code, context=context)
            if write_err:
                last_error = write_err
                attempt_errors.append(last_error)
                break

            final_script_path = script_path
            try:
                context["_code_interpreter_script_path"] = script_path
            except Exception:
                pass

            result = self.executor.run(command=["python", script_path], timeout=self.timeout_seconds)
            if result.success:
                output = (result.stdout or "").strip()
                if not output:
                    output = "Executed successfully (no output)."
                return CodeSolveResult(
                    success=True,
                    output=output,
                    attempts=attempt,
                    script_path=final_script_path,
                    attempt_errors=attempt_errors,
                )

            last_error = self._format_exec_error(result.stderr, result.stdout, result.error)
            attempt_errors.append(last_error)

            if attempt >= self.max_attempts:
                break
            if inline_code:
                # If user gave explicit code, do not mutate it with LLM "repair".
                break
            if not self.llm or not hasattr(self.llm, "generate"):
                break

            repaired = self._repair_code(goal_text, broken_code=code, error_text=last_error, context=context)
            if not repaired or repaired.strip() == code.strip():
                break
            code = repaired

        learned = self._learn_from_gap(goal=goal_text, error=last_error, context=context)
        error_msg = last_error or "Code interpreter failed."
        if learned.get("proposal_id"):
            error_msg += f" Drafted reusable skill proposal: {learned['proposal_id']}."

        return CodeSolveResult(
            success=False,
            error=error_msg,
            attempts=max(1, len(attempt_errors)),
            script_path=final_script_path,
            attempt_errors=attempt_errors,
            learned=learned,
        )

    def _deterministic_solve(self, goal: str) -> Optional[str]:
        """Fast, safe solver for common arithmetic/date tasks."""
        text = str(goal or "").strip()
        if not text:
            return None
        low = text.lower()

        # calculate <expr>
        m = re.search(r"\bcalculate\b\s+(.+)", low)
        if m:
            expr = m.group(1).strip().rstrip("?")
            val = self._safe_arithmetic_eval(expr)
            if val is not None:
                return self._format_number(val)

        # square root of X
        m = re.search(r"square\s+root\s+of\s+(-?\d+(?:\.\d+)?)", low)
        if m:
            x = float(m.group(1))
            if x >= 0:
                return self._format_number(math.sqrt(x))
            return None

        # Fibonacci patterns
        m = re.search(r"(\d+)(?:st|nd|rd|th)?\s+fibonacci", low)
        if not m:
            m = re.search(r"fibonacci(?:\s+number)?\s+(\d+)", low)
        if m:
            n = int(m.group(1))
            if n >= 0:
                a, b = 0, 1
                for _ in range(n):
                    a, b = b, a + b
                return str(a)

        # What is 15% of 200
        m = re.search(r"(-?\d+(?:\.\d+)?)\s*%\s*of\s*(-?\d+(?:\.\d+)?)", low)
        if m:
            p = float(m.group(1))
            x = float(m.group(2))
            return self._format_number((p / 100.0) * x)

        # Convert 100 Fahrenheit to Celsius
        m = re.search(r"convert\s+(-?\d+(?:\.\d+)?)\s+fahrenheit\s+to\s+celsius", low)
        if m:
            f = float(m.group(1))
            c = (f - 32.0) * 5.0 / 9.0
            return self._format_number(c)

        # Days until New Year YYYY
        m = re.search(r"days\s+until\s+new\s+year\s+(\d{4})", low)
        if m:
            year = int(m.group(1))
            try:
                target = date(year, 1, 1)
                return str((target - date.today()).days)
            except Exception:
                return None

        # Current working directory
        if "current working directory" in low or re.search(r"\bcwd\b", low):
            return str(Path.cwd())

        # Random number between A and B
        m = re.search(r"random\s+number\s+between\s+(-?\d+)\s+and\s+(-?\d+)", low)
        if m:
            a = int(m.group(1))
            b = int(m.group(2))
            lo, hi = (a, b) if a <= b else (b, a)
            return str(random.randint(lo, hi))

        # Today's date
        if "today's date" in low or "todays date" in low:
            return date.today().isoformat()

        return None

    def _safe_arithmetic_eval(self, expr: str) -> Optional[float]:
        """Evaluate a plain arithmetic expression safely."""
        allowed_chars = set("0123456789+-*/(). %")
        if any(ch not in allowed_chars for ch in expr):
            return None

        try:
            node = ast.parse(expr, mode="eval")
        except Exception:
            return None

        def _eval(n: ast.AST) -> float:
            if isinstance(n, ast.Expression):
                return _eval(n.body)
            if isinstance(n, ast.Constant) and isinstance(n.value, (int, float)):
                return float(n.value)
            if isinstance(n, ast.Num):  # py<3.8 compatibility
                return float(n.n)
            if isinstance(n, ast.UnaryOp) and isinstance(n.op, (ast.UAdd, ast.USub)):
                v = _eval(n.operand)
                return v if isinstance(n.op, ast.UAdd) else -v
            if isinstance(n, ast.BinOp) and isinstance(
                n.op, (ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod, ast.Pow)
            ):
                left = _eval(n.left)
                right = _eval(n.right)
                if isinstance(n.op, ast.Add):
                    return left + right
                if isinstance(n.op, ast.Sub):
                    return left - right
                if isinstance(n.op, ast.Mult):
                    return left * right
                if isinstance(n.op, ast.Div):
                    return left / right
                if isinstance(n.op, ast.FloorDiv):
                    return left // right
                if isinstance(n.op, ast.Mod):
                    return left % right
                return left ** right
            raise ValueError("unsupported expression")

        try:
            return _eval(node)
        except Exception:
            return None

    def _format_number(self, value: float) -> str:
        if float(value).is_integer():
            return str(int(value))
        return f"{value:.6f}".rstrip("0").rstrip(".")

    def _write_script(self, code: str, context: Dict[str, Any]) -> Tuple[str, str]:
        script_path = ""
        run_id = str((context or {}).get("_run_id") or "").strip()
        if run_id:
            try:
                from .run_manager import get_run_manager

                run_mgr = get_run_manager()
                stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
                script_path = str(run_mgr.write_artifact(run_id, f"code_interpreter_{stamp}.py", code))
            except Exception:
                script_path = ""

        if not script_path:
            try:
                scratch = Path(tempfile.gettempdir()) / "chintu_code_interpreter"
                scratch.mkdir(parents=True, exist_ok=True)
                stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S_%f")
                script_path = str(scratch / f"code_interpreter_{stamp}.py")
                Path(script_path).write_text(code, encoding="utf-8", errors="ignore")
            except Exception as exc:
                return "", f"System Error: failed to write temporary script ({exc})."

        return script_path, ""

    def _extract_inline_code(self, text: str) -> str:
        candidate = str(text or "").strip()
        if not candidate:
            return ""

        if candidate.startswith("```python") or candidate.startswith("```"):
            return self._clean_code(candidate)

        lowered = candidate.lower()
        if lowered.startswith("python:"):
            return self._clean_code(candidate.split(":", 1)[1])

        # Treat multi-line code-like input as direct code.
        has_newline = "\n" in candidate
        looks_like_code = any(
            token in candidate
            for token in (
                "import ",
                "def ",
                "class ",
                "print(",
                "for ",
                "while ",
                "if ",
                "=",
            )
        )
        if has_newline and looks_like_code:
            return self._clean_code(candidate)
        return ""

    def _generate_code(self, goal: str, context: Dict[str, Any]) -> str:
        """Ask LLM to write a standalone script."""
        prompt = f"""
You are an expert Python problem solver.
GOAL: {goal}
CONTEXT: {context}

Write a COMPLETE, STANDALONE Python script that solves the goal.
Rules:
- Focus on logic, math, text processing, and data analysis.
- Prefer standard libraries only: math, datetime, json, random, re, statistics, collections, itertools.
- FORBIDDEN: os, sys, subprocess, socket, requests, eval, exec, __import__, file writes.
- Do not use input().
- Print the final result to stdout.
- Return only raw Python code (no markdown fences).
"""
        response = self.llm.generate(prompt)
        return self._clean_code(response)

    def _repair_code(self, goal: str, broken_code: str, error_text: str, context: Dict[str, Any]) -> str:
        """Ask LLM to repair code after a failed attempt."""
        prompt = f"""
You are fixing a failed Python script.
Goal: {goal}
Context: {context}

Failed script:
```python
{broken_code}
```

Error:
{error_text}

Return a corrected COMPLETE script.
Rules:
- Keep it standalone.
- Keep forbidden modules/functions disallowed: os, sys, subprocess, socket, requests, eval, exec, __import__.
- Return only raw Python code (no markdown).
"""
        try:
            fixed = self.llm.generate(prompt)
        except Exception as exc:
            logger.warning("Code repair generation failed: %s", exc)
            return ""
        return self._clean_code(fixed)

    def _clean_code(self, text: str) -> str:
        """Strip markdown wrappers and normalize."""
        candidate = str(text or "").strip()
        if not candidate:
            return ""
        if candidate.startswith("```python"):
            candidate = candidate.split("```python", 1)[1]
            candidate = candidate.split("```", 1)[0]
        elif candidate.startswith("```"):
            candidate = candidate.split("```", 1)[1]
            candidate = candidate.split("```", 1)[0]

        candidate = candidate.strip()
        if candidate.lower().startswith("python"):
            candidate = candidate[6:].strip()

        common_imports = ["import math", "import datetime", "import json", "import random", "import re"]
        missing_imports: List[str] = []
        for imp in common_imports:
            module_name = imp.split()[-1]
            if f"import {module_name}" not in candidate and f"from {module_name}" not in candidate:
                missing_imports.append(imp)
        if missing_imports:
            candidate = "\n".join(missing_imports) + "\n\n" + candidate
        return candidate.strip() + "\n"

    def _format_exec_error(self, stderr: str, stdout: str, error: Optional[str]) -> str:
        stderr_text = (stderr or "").strip()
        stdout_text = (stdout or "").strip()
        err_text = (error or "").strip()
        chunks = []
        if stderr_text:
            chunks.append(f"stderr={stderr_text[:1200]}")
        if stdout_text:
            chunks.append(f"stdout={stdout_text[:600]}")
        if err_text:
            chunks.append(f"error={err_text[:600]}")
        if not chunks:
            return "Execution failed with unknown error."
        return "Execution Code Error: " + " | ".join(chunks)

    def _is_safe_code(self, code: str) -> Tuple[bool, str]:
        """
        Rigorous AST check for dangerous operations.
        Blocks: OS/network/process modules and dynamic code execution.
        """
        banned_modules = {
            "os",
            "sys",
            "subprocess",
            "shutil",
            "socket",
            "requests",
            "pty",
            "commands",
            "pickle",
            "marshal",
            "ctypes",
            "importlib",
            "pathlib",
        }
        banned_functions = {"eval", "exec", "__import__", "compile", "open", "setattr", "getattr", "delattr"}
        dangerous_attrs = {
            "system",
            "popen",
            "spawn",
            "fork",
            "remove",
            "unlink",
            "rmdir",
            "rmtree",
            "rename",
            "replace",
            "chmod",
            "chown",
            "write_text",
            "write_bytes",
        }

        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name.split(".")[0] in banned_modules:
                            return False, f"Banned import detected: {alias.name}"
                if isinstance(node, ast.ImportFrom):
                    if node.module and node.module.split(".")[0] in banned_modules:
                        return False, f"Banned from-import detected: {node.module}"
                if isinstance(node, ast.Call):
                    if isinstance(node.func, ast.Name) and node.func.id in banned_functions:
                        return False, f"Banned function call detected: {node.func.id}"
                    if isinstance(node.func, ast.Attribute) and node.func.attr in banned_functions:
                        return False, f"Banned attribute function detected: {node.func.attr}"
                if isinstance(node, ast.Attribute) and node.attr in dangerous_attrs:
                    return False, f"Dangerous attribute detected: {node.attr}"
            return True, ""
        except SyntaxError:
            return False, "Syntax error in generated code."
        except Exception as exc:
            logger.error("Security analysis failed: %s", exc)
            return False, f"Internal security error: {exc}"

    def _learn_from_gap(self, goal: str, error: str, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Persist failure context and optionally draft a future skill proposal.
        This keeps repeated failures actionable instead of silent.
        """
        learned: Dict[str, Any] = {}
        if not goal:
            return learned

        try:
            from ..brain.learning.learning_engine import get_learning_engine

            le = get_learning_engine()
            le.record_gap(
                gap=f"Code interpreter gap for goal '{goal[:220]}': {str(error or '')[:600]}",
                context={"source": "code_interpreter"},
            )
            learned["gap_recorded"] = True
        except Exception:
            learned["gap_recorded"] = False

        if bool(getattr(self.config, "learning_auto_web_on_gap", True)):
            try:
                from chintu_backend.search.search_capabilities import search_web
                from ..brain.learning.learning_engine import get_learning_engine

                q = f"python fix {goal[:120]} {str(error or '')[:120]}".strip()
                raw_results, formatted = search_web(q, max_results=3)
                sources: List[str] = []
                for item in raw_results or []:
                    url = getattr(item, "url", None)
                    if url:
                        sources.append(str(url))
                get_learning_engine().record_web_learning(
                    query=q,
                    response=str(formatted or "")[:4000],
                    sources=sources,
                )
                learned["web_learning_recorded"] = True
                learned["web_sources"] = sources[:10]
            except Exception:
                learned["web_learning_recorded"] = False

        if bool(getattr(self.config, "learning_auto_propose_skill_on_gap", True)):
            try:
                from ..capabilities.active_learning import get_active_learner

                topic = goal[:80]
                msg = get_active_learner().learn_skill(topic)
                learned["proposal_message"] = msg
                match = re.search(r"(proposal_[a-z0-9_-]+)", msg.lower())
                if match:
                    learned["proposal_id"] = match.group(1)
            except Exception:
                pass

        # Surface a short marker for downstream UI/logs
        if "proposal_id" in learned:
            learned["summary"] = f"Drafted skill proposal {learned['proposal_id']} for this gap."
        elif learned.get("web_learning_recorded"):
            learned["summary"] = "Recorded gap and web-learning evidence for future tuning."
        elif learned.get("gap_recorded"):
            learned["summary"] = "Recorded learning gap for future tuning."
        return learned


_interpreter: Optional[CodeInterpreter] = None


def get_code_interpreter(llm_client=None) -> CodeInterpreter:
    global _interpreter
    if not _interpreter:
        _interpreter = CodeInterpreter(llm_client)
    return _interpreter
